from dlt.helpers.streamlit import write_data_explorer_page

from _helpers import pipeline


# generates sidebar with information on the tables that were generated by the pipeline
# adds a text area to run queries against them
def write():
    return write_data_explorer_page(pipeline)